apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "wallabag.fullname" . }}
  labels:
    app: {{ template "wallabag.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  domainName: {{ .Values.domainName }}
  {{- if eq .Values.database.driver "pdo_pgsql"}}
  dataBase: "PostgresQL"
  {{- else if eq .Values.database.driver "pdo_mysql" }}
  dataBase: "MySQL"
  {{ else }}
  dataBase: "SQLite"
  {{- end }}