{{- if .Values.ingress.enabled - }}
apiVersion: networking.k8s.io/v1beta1
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  labels:
{{- range $key, $value := .Values.ingress.extraLabels }}
    {{ $key }}: {{ $value }}
{{- end }}
  name:
    name: {{ template "prometheus.server.fullname" . }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ template "wallabag.fullname" . }}
              servicePort: {{ .Values.service.port }}
    {{- end -}}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
