apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wallabag.fullname" . }}
  labels:
    app: {{ template "wallabag.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:  
  {{- if eq .Values.database.driver "pdo_pgsql"}}
  postgres-password:  {{ required "Password for PostresQL database required" .Values.postgresPassword | b64enc | quote }}
  postgres-user:  {{ required "PostgresQL user required"  .Values.postgresUser | b64enc | quote }}
  {{- else if eq .Values.database.driver "pdo_mysql" }}
  mysql-root-password:  {{ required "Root password for MySQL database required" .Values.mysqlRootPassword | b64enc | quote }}
  {{- end }}

  {{- if or (eq .Values.database.driver "pdo_pgsql") (eq .Values.database.driver "pdo_mysql")}}
  database-host: {{ required "Database host is required" .Values.database.host | b64enc | quote }}
  database-port: {{ required "Database port is required" .Values.database.port | b64enc | quote }}
  {{- else }}
  database-host: {{ .Values.database.host | default "127.0.0.1" | b64enc | quote }}
  {{- end }}
  database-name: {{ .Values.database.name | b64enc | quote }}
  database-user: {{ .Values.database.user | b64enc | quote }}
  database-password: {{ .Values.database.password | b64enc | quote}}
  database-driver: {{ .Values.database.driver | b64enc | quote}}